[build]
publish = "frontend/dist"

[context.production]
command = "cd frontend && npm run build"

[context.deploy-preview]
command = "cd frontend && npm run build"

[redirects]
from = "/api/*"
to = "https://agrobid-backend.onrender.com/api/:splat"
status = 200

from = "/*"
to = "/index.html"
status = 200
